// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Common.ExceptionLogger")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Common.HostAuthStateProvider")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Common.JwtTokenParser")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.DepartmentComponents.CreateDepartmentModalComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.DepartmentComponents.DeleteDepartmentModalComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.DepartmentComponents.DepartmentDetailsModalComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.DepartmentComponents.DepartmentListComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.DepartmentComponents.UpdateDepartmentModalComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.EmployeeComponents.CreateEmployeeModalComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.EmployeeComponents.DeleteEmployeeModalComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.EmployeeComponents.EmployeeDetailsModalComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.EmployeeComponents.EmployeeListComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.EmployeeComponents.UpdateEmployeeModalComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.IdentityComponents.ForgotPasswordComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.IdentityComponents.LoginComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.IdentityComponents.RegisterComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Components.SharedComponents.MainLayoutComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.DepartmentModels.CreateDepartmentModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.DepartmentModels.DepartmentDetailsModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.DepartmentModels.UpdateDepartmentModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.EmployeeModels.CreateEmployeeModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.EmployeeModels.EmployeeDetailsModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.EmployeeModels.UpdateEmployeeModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.ChangePasswordModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.EditUserModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.LoginModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.RegistrationModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.RoleModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.SetUserPasswordModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.UserDetailsModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.UserModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.IdentityModels.UserSearchModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.PaginatedList`1")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Models.SelectListItem")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Services.DepartmentService")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Services.EmployeeService")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Blazor.Services.UserService")]
