version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
       SA_PASSWORD: "MyPass@word"
       ACCEPT_EULA: "Y"
       MSSQL_PID: 'Express'
    ports: ["1440:1433"]
    
  cleanhr.api:
    image: ${DOCKER_REGISTRY-}cleanhrapi
    build:
      context: .
      dockerfile: src/ServerApp/Presentation/CleanHr.Api/Dockerfile
    ports: ["7100:80","7101:443"]
    depends_on: ["sqlserver"]

