// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Not Applicable here.", Scope = "namespaceanddescendants", Target = "~N:CleanHr.Api.Features.User.Endpoints")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Not Applicable here.", Scope = "namespaceanddescendants", Target = "~N:CleanHr.Api.Features.Employee.Endpoints")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Not Applicable here.", Scope = "namespaceanddescendants", Target = "~N:CleanHr.Api.Features.Department.Endpoints")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "Not Applicable here.", Scope = "namespaceanddescendants", Target = "~N:CleanHr.Api.Endpoints")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Configs.JwtConfig")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.EmployeeBaseModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Endpoints.CreateDepartmentEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Endpoints.DeleteDepartmentEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Endpoints.DepartmentEndpointBase")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Endpoints.GetDepartmentByIdEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Endpoints.GetDepartmentListEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Endpoints.GetDepartmentSelectListEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Endpoints.UpdateDepartmentEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Models.CreateDepartmentModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Models.DepartmentBaseModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Department.Models.UpdateDepartmentModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Employee.Endpoints.CreateEmployeeEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Employee.Endpoints.DeleteEmployeeEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Employee.Endpoints.EmployeeEndpointBase")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Employee.Endpoints.GetEmployeeDetailsByIdEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Employee.Endpoints.GetEmployeeListEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Employee.Endpoints.UpdateEmployeeEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Employee.Models.CreateEmployeeModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.Employee.Models.UpdateEmployeeModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.ExternalLogin.Endpoints.ExternalLoginEndpointBase")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.ExternalLogin.Endpoints.ExternalLoginSignInCallbackEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.ExternalLogin.Endpoints.ExternalLoginSignInEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.ExternalLogin.Endpoints.ExternalLoginSignUpCallbackEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.ExternalLogin.Endpoints.ExternalLoginSignUpEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.ConfirmUserEmailEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.GetRefreshedAccessTokenEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.ResendUserEmailConfirmationCodeEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.ResetUserPasswordEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.SendUserPasswordResetCodeEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.UserEndpointBase")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.UserLoginEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.UserLogoutEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Endpoints.UserRegistrationEndpoint")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Models.EmailConfirmationModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Models.ForgotPasswordModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Models.LoginModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Models.RegistrationModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Models.ResendEmailConfirmationCodeModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Models.ResetPasswordModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Features.User.Models.TokenRefreshModel")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.Helpers.JwtTokenManager")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:CleanHr.Api.TestModel")]
